userapp/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import (DeleteUser,auth_register,EditUserDetail,signin,ListDetail,listuserdetail)
from django.contrib.auth.views import LogoutView
from django.urls import path,include
from django.contrib.auth.decorators import login_required
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

app_name = 'userapp'
urlpatterns =[
    path('login/',signin,name='auth-login'),
    path('api/',ListDetail.as_view(),name='api'),
    path('logout/',LogoutView.as_view(template_name='userapp/signout.html'),name='auth-logout'),
    path('register/',auth_register,name='auth-register'),
    path('',listuserdetail,name='home'),
    path('edit/<int:pk>',EditUserDetail.as_view(),name='edit'),
    path('delete/<int:pk>',DeleteUser.as_view(),name='delete'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

usermanagerproj/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('userapp.urls')),

]

userapp/models.py
from django.contrib.auth.models import AbstractUser,AbstractBaseUser,PermissionsMixin
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from .managers import CustomUserManager


class CustomUser(AbstractBaseUser,PermissionsMixin):
    username = models.CharField(max_length=20,unique=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    first_name = models.CharField(_('first name'), max_length=25)
    last_name = models.CharField(_('last name'), max_length=25)
    address = models.CharField(max_length=200,null=False,blank=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['password']

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class Token(models.Model):
    user = models.OneToOneField(CustomUser,blank=False,on_delete=models.CASCADE)
    token_key = models.CharField(max_length=500,default='')

    def __str__(self):
        return str(self.user)
    

userapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from django.forms import ModelForm,Form

class SignUpForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1','password2','address']

class SignInForm(ModelForm):
    class Meta:
        model = CustomUser
        fields = ['email','password']

class EditForm(ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email','first_name', 'last_name','address']

userapp/views.py
from django.shortcuts import render,redirect
from .models import CustomUser
from .forms import SignUpForm,EditForm
from django.views.generic import DeleteView,UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from rest_framework.views import APIView
from .serializers import ListDetailSerailizer
from rest_framework.response import Response
from rest_framework_simplejwt.authentication import JWTAuthentication
from rest_framework.permissions import IsAuthenticated
from django.contrib.auth.decorators import login_required
from rest_framework.status import HTTP_401_UNAUTHORIZED
import requests
import datetime
# Create your views here.
class ListDetail(APIView):
    authentication_classes=[JWTAuthentication]
    permission_classes=[IsAuthenticated]
    def get(self,request):
        user=CustomUser.objects.filter(is_staff=False)
        serializer = ListDetailSerailizer(user,many=True)
        return Response({'result':serializer.data})


def auth_register(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        forms = SignUpForm()
        if request.method == 'POST':
            forms = SignUpForm(request.POST)
            print ('Register')
            if forms.is_valid():
                forms.save()
                return redirect('userapp:auth-login')
    return render(request, 'userapp/register.html',{'forms': forms,})


def signin(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        if request.method == 'POST':
                email = request.POST.get('email')
                password = request.POST.get('password')
                user=authenticate(request,username=email,password=password)
                if user is not None:
                        login(request,user)
                        resp= requests.post("https://userjwtauth.herokuapp.com/api/token/",
                        data={'email':email, 'password':password}).json()
                        token=(resp['access'])
                        customuser = CustomUser.objects.filter(email=email).first()
                        print(customuser.id)
                        customuser.token.user=customuser
                        customuser.token.token_key=token
                        customuser.save()
                        messages.success(request,'You have successfully Logined for 5 minutes')
                        return redirect('/')
                else:
                        messages.error(request,"username or password is incorrect")
                        return redirect('userapp:auth-login')
    return render(request,'userapp/signin.html')

@login_required(login_url='/login')
def listuserdetail(request):
        customuser=CustomUser.objects.get(id=request.user.id)
        resp=requests.get("https://userjwtauth.herokuapp.com/api/",headers={'Authorization':'Bearer '+customuser.token.token_key})
        if resp.status_code == HTTP_401_UNAUTHORIZED:
            logout(request)
            return redirect('login/')
        else:
            print(resp.json())
            return render(request,'userapp/index.html',{'response':resp.json()['result']})
        
        

class EditUserDetail(LoginRequiredMixin,UpdateView):
    model = CustomUser
    context_object_name='users'
    form_class = EditForm
    template_name='userapp/edit-detail.html'
    success_url = '/'

class DeleteUser(LoginRequiredMixin,DeleteView):
    model = CustomUser
    context_object_name='users'
    template_name='userapp/delete.html'
    success_url='/'
    success_message = "Deleted Successfully"

userapp/templates/userapp/delete.html
{% extends 'userapp/main.html' %} {% block title %}{{order}} Order{% endblock title %}
{% load crispy_forms_tags %}
{%block content %}
<div class="container my-2  p-2">
   <div class="row p-3 justify-content-center">
        <div class="col-sm-6 border p-4">
    <form class="form " action="#" method="Post">
        {% csrf_token %}
        <p>Are you sure you want to delete this account *{{users.username}}* ?</p>
        <a href="{% url 'userapp:home' %}" class="btn btn-sm mt-2 btn-outline-secondary">Cancel</a>
        <input type="submit" name="submit" value="Delete" class="btn btn-sm mt-2 btn-danger">
    </form>
</div>
</div>
</div>
{% endblock content %}

userapp/templates/userapp/edit-detail.html
{% extends 'userapp/main.html' %} 
{% block title %}{{label}}{% endblock title %}
{% load crispy_forms_tags %}
{%block content %}
<div class="container-fluid  my-2 mx-2 p-2">
<div class="row justify-content-center p-2">
<div class="col-6">
        <p class="alert alert-primary">Update User Detail</p>
    <form class="form" method="Post">
        {% csrf_token %}
       {{form}}
        <input type="submit" name="submit" value="Update" class="btn btn-md mt-2 btn-primary">
    </form>
</div>
</div>
</div>
{% endblock content %}

userapp/templates/userapp/index.html
{% extends 'userapp/main.html' %}
{% block title %}Home{% endblock title %}
{% block content %}

<div class="container-fluid">
{% if messages %}
     {% for message in messages %}
        <div class="col alert alert-{{message.tags}} p-2 mt-2">
            {{ message }} <span>:)</span>
        </div>
    {% endfor %}
{% endif %}
    <div class="container-fluid mt-2">  <!--table design-->
        <div class="row">
            <div class="col">
                <table class="table table-striped table-hover user-select-none">
                    <thead class="thead-dark">
                            <tr class="">
                                <th colspan="5" class="text-center" >User Details</th>
                            </tr>
                            <tr class="">
                                <th>Id</th>
                                <th>Username</th>
                                <th>Email</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                    </thead>
                    <tbody>
                             {% for resp in response %}
                            <tr class="table-success">
                         
                                <td class="">{{resp.id}}</td>
                                <td class="">{{resp.username}}</td>
                                <td class="">{{resp.email}}</td>
                            
                                <td class=""><a href="{% url 'userapp:edit' resp.id%}">Edit</a></td>
                                <td class=""><a href="{% url 'userapp:delete' resp.id%}">Delete</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
{% endblock content %}

userapp/templates/userapp/main.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>{% block title %}{% endblock title %}</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    {% load static %}
    <link rel='icon' href={% static 'userapp/img/cart.svg' %}>
    <link rel='stylesheet' type='text/css' media='screen' href={% static 'userapp/css/bootstrap.css' %}>
    <link rel='stylesheet' type='text/css' media='screen' href={% static 'userapp/css/main.css' %}>
</head>
<body>
    <header id="header" class="sticky-top bg-dark align-items-baseline">
      {% if user.is_authenticated %}
      <h1><a href="#" class="text-white">Welcome Back! <span class="text-warning">{{user.email}} :)<span></a></h1>
        {% else %}
        <h1><a href="#" class="text-white">Oops! <span class="text-warning">{{user.email}} :(<span></a></h1>
      {% endif %}
      <nav class="nav-bar " >
          <a href={% url 'userapp:home' %}>Dashboard</a>
       {% if user.is_authenticated %}
         <a href={% url 'userapp:auth-logout' %}>Logout</a>
       {% else %}
        <a href={% url 'userapp:auth-login' %}>Login</a>
        <a href={% url 'userapp:auth-register' %}>Register</a>
       {% endif %}
        {% comment %} <a href={% url 'book:login' %}>Login</a> {% endcomment %}
      </nav>
      
    </header>
    {% block content %}
    {% endblock content %}
</body>
</html>

userapp/templates/userapp/register.html
{% extends 'userapp/main.html' %} 
{% block title %} Register {% endblock title %}
{% load crispy_forms_tags %}
{%block content %}
<div class="conatiner">
  <form method="post">
    {% csrf_token %}
    <div class="row p-3 justify-content-center">
        <div class="col-sm-6 border p-4">
          <div class="form-group form-input ">
              {{forms|crispy}}
           
          </div>
          <div class="form-group text-center">
            <input type="submit" value="Register" class=" btn btn-primary">
          </div>
          <div class="form-group text-center">
            <a href="{% url 'userapp:auth-login' %}" class="text-right">Already have an account? Login</a>
          </div>
        </div>
      </div>
  </form>
</div>


{% endblock %}

userapp/templates/userapp/signin.html
{% extends 'userapp/main.html' %} {% block title %} Login {% endblock title %}
{% load crispy_forms_tags %}
{%block content %}
<div class="conatiner m-4">
    
  <form method="POST">
  
  <div class="row p-2 justify-content-center">
      <div class="col-md-6 border p-5">
        {% csrf_token %}
        {% for message in messages %}
          {% if message.tags == 'error' %}
            <div class="col alert alert-danger p-2 mt-2 ">
              {{ message }} <span>:(</span>
            </div>
          {% endif %}
        {% endfor %}
        <div class="form-group form-input ">
        <input type="email" class="form-control" placeholder="Email address*" name="email" >
        </div>
        <div class="form-group form-input ">
        <input type="password" class="form-control" placeholder="Password*" name="password" >
        </div>
        <div class="form-group text-center">
          <input type="submit" value="Login"class=" btn btn-md btn-primary">
        </div>
        <div class="form-group text-center">
          <a class="text-right" href={% url 'userapp:auth-register' %}>Don't have an account? Register</a>
        </div>
      </div>
    </div>
  </form>
</div>

{% endblock %}

userapp/templates/userapp/signout.html
{% extends 'userapp/main.html' %} {% block title %} Logout {% endblock title %}
{% load crispy_forms_tags %}
{%block content %}

<div class="container border p-3 my-3">
    <div class="row text-center">
        <div class="col-12 p-0">
            <p class="display border-bottom p-2">You have been Logged out</p>
        </div>
        <div class="col-12 p-0 ">
            <p>
                <a href="{% url 'userapp:auth-login' %}" class="text-right">Sign-in Again</a>
            </p>
        </div>
    </div>
</div>

{% endblock %}